### ISSUE TITLE
TypeError: makedirs() got an unexpected keyword argument 'exist_ok' with Python 2.7

### ISSUE THREAD

**Issue by jameshanlon** [silentsokolov/flask-thumbnails#10]
See line 32 of  flask-thumbnails/flask_thumbnails/storage_backends.py.

The 'exist_ok' argument is Python 3 only.

**Comment by bostrt** [comment]
https://github.com/silentsokolov/flask-thumbnails/blob/master/flask_thumbnails/storage_backends.py#L32

exist_ok is exists in Python 3.2+ https://docs.python.org/3/library/os.html#os.makedirs

Not sure if this flask-thumbnails is intended to support 3.1 and 3.0 though.

**Comment by silentsokolov** [comment]
We run test with python versions:
```yml
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
```

3.0, 3.1, 3.2, 3.3 versions has deprecated in many system, pls upgrade or fork repo ... (( sorry.

**Comment by bostrt** [comment]
Oh, but @jameshanlon means specifcally for Python 2.7 where `exists_ok` is not present: https://docs.python.org/2/library/os.html#os.makedirs

(disclaimer: I hadn't had my coffee yet when answering earlier)

**Comment by jameshanlon** [comment]
@silentsokolov The bug only affects Python 2.7, which, according to your testing should be supported.

**Comment by bostrt** [comment]
Check out https://github.com/bostrt/flask-thumbnails/commit/0769cd3569a2c60c814f2abae068eb8d0f227187#commitcomment-22870805 

Hope it helps :smiley_cat:

**Comment by silentsokolov** [comment]
@jameshanlon Fail, sorry 😭  Please, update to 1.0.2.

@bostrt This is a serious bug, I did not wait PR, but I appreciate your help, thx
