### ISSUE TITLE
thumbnail_filepath in get_thumbnail function incorrect calculated

### ISSUE THREAD

**Issue by Goomba41** [silentsokolov/flask-thumbnails#16]
In Option settings said, as i understand, i can set  THUMBNAIL_MEDIA_THUMBNAIL_ROOT and thumbs will be saved there.

So i set:

ROOT_PATH = os.path.join('/home/devadmin','.cdnstatic')
THUMBNAIL_MEDIA_ROOT = ROOT_PATH
THUMBNAIL_MEDIA_THUMBNAIL_ROOT = os.path.join(ROOT_PATH,'.thumbnails')

So, paths will be:
/home/devadmin/.cdnstatic
/home/devadmin/.cdnstatic/.thumbnails

My originals saved in other path:

/home/devadmin/.cdnstatic/digital_image/1023/68/1-first.jpeg

Next, function calculated parameters:

original_filepath = os.path.join(self.root_directory, original_path, original_filename)
That is correct: /home/devadmin/.cdnstatic/digital_image/1023/68/1-first.jpeg

But:
thumbnail_filepath = os.path.join(self.thumbnail_directory, original_path, thumbnail_filename)
calculated as: /home/devadmin/.cdnstatic/digital_image/1023/68/<thumbnail_filename>

So my thumbs saved in same directory as originals. I try to swap <self.thumbnail_directory> and <original_path> (i think need to remove <original_path>), then it calculated as i expected: /home/devadmin/.cdnstatic/.thumbnails/<thumbnail_filename>

Same for thumbnail_url function

Can you fix this, or am I wrong and am doing something wrong?

**Comment by silentsokolov** [comment]
Sorry, I dont understand ((

I used code below for test:
```python
import os

from flask import Flask, render_template, send_from_directory
from flask_thumbnails import Thumbnail
from werkzeug.routing import BaseConverter

app = Flask(__name__)

class RegexConverter(BaseConverter):
    def __init__(self, url_map, *items):
        super(RegexConverter, self).__init__(url_map)
        self.regex = items[0]

app.url_map.converters['regex'] = RegexConverter
thumb = Thumbnail(app)

ROOT_PATH = os.path.join('<my/path>/img','.cdnstatic')
app.config['THUMBNAIL_MEDIA_ROOT'] = ROOT_PATH
app.config['THUMBNAIL_MEDIA_THUMBNAIL_ROOT'] = os.path.join(ROOT_PATH,'.thumbnails')

app.config['THUMBNAIL_MEDIA_URL'] = '/media/'
app.config['THUMBNAIL_MEDIA_THUMBNAIL_URL'] = '/media/thumb/'


@app.route('/')
def hello_world():
    return render_template('index.html')


@app.route('/media/thumb/<regex("([\w\d_/-]+)?.(?:jpe?g|gif|png)"):filename>')
def media_file(filename):
    return send_from_directory(app.config['THUMBNAIL_MEDIA_THUMBNAIL_ROOT'], filename)
```

Template:

```html
<html>
    <head>
        <title>Test</title>
    </head>
    <body>
        <img src="{{ 'digital_image/1.png'|thumbnail('200x200') }}" alt="" />
    </body>
</html>
```

Paths in app's code:

```
...
print(original_filepath)
print(thumbnail_filepath)
...

<my/path>/img/.cdnstatic/digital_image/1.png
<my/path>/img/.cdnstatic/.thumbnails/digital_image/1_200x200_fit_90.png
```

Thumbnail has created. Thumbnail's folder has  created. And server has sent file:
`127.0.0.1 - - [**/Jan/2021 10:51:50] "GET /media/thumb/digital_image/1_200x200_fit_90.png HTTP/1.1" 200 -`

**Comment by Goomba41** [comment]
Hi! Thanks for answer! You can watch part of my code [here](https://github.com/Goomba41/cdn.cgako/blob/main/api.py) (from string 506). I think problem is i call "get_thumbnail" function manually and send full file path, not relative. Unlike you, you used it in template (in <img>) and send relative path. So function try to join full paths (in order thumbnail_directory, original_path, thumbnail_filename):

/home/devadmin/.cdnstatic/.thumbnails
                            +
/home/devadmin/.cdnstatic/digital_image/1023/68/
                            +
1.png

And resulted path is:
/home/devadmin/.cdnstatic/digital_image/1023/68/1.png and thumb create nearby original file

**Comment by silentsokolov** [comment]
Yep, need a relative path. 

But it isn't a `flask-thumbnails`'s problem. I close this issue.

Reopen if you will get bug.

Thx
